"""empty message

Revision ID: 1dea6fe231aa
Revises: 332e038619fe
Create Date: 2020-04-04 18:40:01.708453

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1dea6fe231aa'
down_revision = '332e038619fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    data = [{
        "id": 1,
        "website": "https://www.gunsnpetalsband.com",
    }]
    connection = op.get_bind()

    for item in data:
        op.get_bind().execute(sa.sql.text("UPDATE \"Artist\" SET website = :website WHERE id = :id"), **item)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
