"""empty message

Revision ID: 332e038619fe
Revises: bb4da1a4e13b
Create Date: 2020-04-04 17:04:38.839322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332e038619fe'
down_revision = 'bb4da1a4e13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    data = [
        {
            "id": 1,
            "genres": ["Jazz", "Reggae", "Swing", "Classical", "Folk"]
        },
        {
            "id": 2,
            "genres": ["Classical", "R&B", "Hip-Hop"]
        },
        {
            "id": 3,
            "genres": ["Rock n Roll", "Jazz", "Classical", "Folk"]
        }
    ]
    connection = op.get_bind()

    for item in data:
        op.get_bind().execute(sa.sql.text("UPDATE \"Venue\" SET genres = :genres WHERE id = :id"), **item)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
